# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dalton Amateur Radio Club

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
  Seeking to advance the state of art and science of amateur radio communications through education, training, experimentation, and research.
  Promoting the free interchange of technical information among and between amateur radio operators and the general public.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://w4drc.com" # the base hostname & protocol for your site

#These settings might be able to go?
#author: David Boyne
#twitter_username: boyney123
#github_username:  boyney123/evento
#company_name: Comparethemarket

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

#lychee:
#  url: http://gallery.w4drc.gaampr.net
#  album_title_tag: h1
#  link_big_to: lychee